### ISSUE TITLE
It doesn't imports images. Only the import file.

### ISSUE THREAD

**Issue by IAMSTANDARD** [hhyyrylainen/GodotPckTool#22] opened 2022-09-20 08:49 UTC
I used it on a pck of a web build. But it did not extract the images, only the import files for the images.

**Comment by hhyyrylainen** [comment] 2022-09-20 08:53
Duplicate of: https://github.com/hhyyrylainen/GodotPckTool/issues/7

**Closed by hhyyrylainen** 2022-09-20 08:53 UTC

**Comment by IAMSTANDARD** [comment] 2022-09-21 12:11
But it seems like they didn't reach at any conclusion?

**Comment by hhyyrylainen** [comment] 2022-09-21 12:13
But this is still the same exact feature request, of wanting to do further processing on the files rather than just extracting the files that are contained in a .pck.
